version: "3.7"
services:
  backend:
    container_name: pocketbase
    environment:
      - SU_EMAIL=${PB_ADMIN_EMAIL}
      - SU_PASSWORD=${PB_ADMIN_PASSWORD}
    build:
      context: ../pocketbase
      args:
        - VERSION=${PB_VERSION}
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - pb_data:/usr/local/bin/pb_data

  web:
    container_name: web
    build:
      context: ../apps/web
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - backend
volumes:
  pb_data:
